<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forgot your password</name>
   <tag></tag>
   <elementGuidId>dcb57167-a8b1-4ce5-b2e1-1f9d7e3f00b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.policy > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hs_cos_wrapper_module_71538058904']/div[3]/div/form/div[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c4aeeeb9-e17e-4fe6-9ce6-ab9d06ccd684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>40e2863a-7cc5-448f-a946-f8411e0c7f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://my.katalon.com/login?view=forgot_password</value>
      <webElementGuid>b8397ed6-82ce-478b-af86-923b5657c08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot your password?</value>
      <webElementGuid>c5fc1dc6-1972-41c3-90bb-3d2b92706b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hs_cos_wrapper_module_71538058904&quot;)/div[@class=&quot;sign_up_section&quot;]/div[@class=&quot;sign_up_form&quot;]/form[@class=&quot;form_sign_up&quot;]/div[@class=&quot;policy&quot;]/a[1]</value>
      <webElementGuid>896409f2-8320-40a1-8c85-dea62eb4ed2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hs_cos_wrapper_module_71538058904']/div[3]/div/form/div[4]/a</value>
      <webElementGuid>1602766e-18dd-4b0f-9511-a93407a4f0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot your password?')]</value>
      <webElementGuid>59b4ec61-a56b-4c0a-88cc-68a12e5fa0e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incorrect email or password. Please try again'])[1]/following::a[1]</value>
      <webElementGuid>a20eaaf0-b510-4709-9e96-3b1b6484e1a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do not allow space'])[1]/following::a[1]</value>
      <webElementGuid>e8c8a031-ed23-4bea-9f3d-468766bd46d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One Katalon Account for everything'])[1]/preceding::a[1]</value>
      <webElementGuid>51de48d0-a2ba-4c2b-b367-c8a7a56b1788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/preceding::a[2]</value>
      <webElementGuid>384a6e07-0644-4e74-98e0-6538eccfb02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot your password?']/parent::*</value>
      <webElementGuid>0086fce6-e1fe-4994-89a7-ae05d254331f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://my.katalon.com/login?view=forgot_password')]</value>
      <webElementGuid>451348fe-0f4f-45e0-a5b0-b335c1ea074f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>c9254ce6-510c-4039-86b2-a07aa5ee29a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://my.katalon.com/login?view=forgot_password' and (text() = 'Forgot your password?' or . = 'Forgot your password?')]</value>
      <webElementGuid>15d62b56-f3b1-4901-850a-b5d37bbea36b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
