<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Email_a-a37836snguz1</name>
   <tag></tag>
   <elementGuidId>02205e64-8539-418f-a719-9404fc435d6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-a37836snguz1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-a37836snguz1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f8186f5f-3387-4b57-acdb-c21b006bb73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>19a7e5ee-21ae-4308-86da-0ec1893176a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lc_Gt4ZAAAAAOm9_29UIGEij29l1W7MMGxvSOSU&amp;co=aHR0cHM6Ly9teS5rYXRhbG9uLmNvbTo0NDM.&amp;hl=en&amp;type=image&amp;v=CHIHFAf1bjFPOjwwi5Xa4cWR&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=cr1llsdg0iy2</value>
      <webElementGuid>85ff8cad-f330-42b0-9201-3935e9889625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>e3d7b8fa-f013-48a4-b1d7-3e0a9f770ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>adbd3f37-cb9f-44d7-a28b-1ea34c29d2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>a2f4064d-8b7e-4fef-ada6-be60ddbbde6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-a37836snguz1</value>
      <webElementGuid>2e7e192d-566a-4ea1-aaeb-7c69af50ba7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>930bedbf-2c7d-482c-9001-70cdf36c0eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>de44e35c-2239-4b83-a476-e0208b47ee30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>c435e86b-811a-4741-a714-baa37aa6c804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgot-password-form&quot;)/div[2]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>4e8cf037-8162-47d2-8e36-e498872a5341</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-a37836snguz1']</value>
      <webElementGuid>162648a6-38d8-4a1a-a233-f80ef79d972d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='forgot-password-form']/div[2]/div/div/div/iframe</value>
      <webElementGuid>0f48cf03-6464-4078-ad9e-b3a163bc772e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>23935ca4-73f0-4f1f-9459-b5e9a8942436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lc_Gt4ZAAAAAOm9_29UIGEij29l1W7MMGxvSOSU&amp;co=aHR0cHM6Ly9teS5rYXRhbG9uLmNvbTo0NDM.&amp;hl=en&amp;type=image&amp;v=CHIHFAf1bjFPOjwwi5Xa4cWR&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=cr1llsdg0iy2' and @name = 'a-a37836snguz1']</value>
      <webElementGuid>0529fd1b-2051-4c26-a07b-d41cac9fbbb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
