<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Email_a-t5jb7gxc08xt</name>
   <tag></tag>
   <elementGuidId>2b3c2a9f-d707-41d1-ae74-89a127a6c629</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-t5jb7gxc08xt&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-t5jb7gxc08xt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>60d05072-33a6-400c-9586-509aaa1ec36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>0116f152-b1b5-4639-a40e-a20b94355c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lc_Gt4ZAAAAAOm9_29UIGEij29l1W7MMGxvSOSU&amp;co=aHR0cHM6Ly9teS5rYXRhbG9uLmNvbTo0NDM.&amp;hl=en&amp;type=image&amp;v=CHIHFAf1bjFPOjwwi5Xa4cWR&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=y1q9ii8c9ozw</value>
      <webElementGuid>e20bcfdd-58eb-4b70-8129-1f3369858197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>1552ed5c-4a5e-41b7-9d21-8a9c9b356e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>fbd0909f-ced1-44fe-89e6-80c330c147ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>39e64e58-cf51-49bf-9f4c-c1177fb4f65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-t5jb7gxc08xt</value>
      <webElementGuid>4cd47cf5-e4a1-4bf0-b3f7-3a4f2b49d128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3f8b508c-6508-4d98-89bb-f4d25b314b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>b2575c48-b7ac-4da2-ae5f-d85c4072f1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>b7fde01c-36f7-400f-9d53-ee26787572e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgot-password-form&quot;)/div[2]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>36c3fa6d-deba-4de7-a0d8-29acdcca2cda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-t5jb7gxc08xt']</value>
      <webElementGuid>0bf7ce70-2b98-471b-bfc3-7fff5b5bd899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='forgot-password-form']/div[2]/div/div/div/iframe</value>
      <webElementGuid>2cc524ba-02e5-4b23-a401-0b1243e1feeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>04f6c859-20d9-423f-bd5d-1b74222efc7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lc_Gt4ZAAAAAOm9_29UIGEij29l1W7MMGxvSOSU&amp;co=aHR0cHM6Ly9teS5rYXRhbG9uLmNvbTo0NDM.&amp;hl=en&amp;type=image&amp;v=CHIHFAf1bjFPOjwwi5Xa4cWR&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=y1q9ii8c9ozw' and @name = 'a-t5jb7gxc08xt']</value>
      <webElementGuid>c930ad39-8e81-454c-88d1-83801460ed8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
