<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(I didn, , t get the email)_a-_65066b</name>
   <tag></tag>
   <elementGuidId>1bd969e4-dae5-45b7-b7f6-7e25a46b7ce8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-psxfltpo60cc&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-psxfltpo60cc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>eb915bb9-10db-4584-a1fa-093b6ec399e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>07486e77-a30f-4ddb-9f5e-709c5383c124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lc_Gt4ZAAAAAOm9_29UIGEij29l1W7MMGxvSOSU&amp;co=aHR0cHM6Ly9teS5rYXRhbG9uLmNvbTo0NDM.&amp;hl=en&amp;type=image&amp;v=CHIHFAf1bjFPOjwwi5Xa4cWR&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=dinu3gjeidv8</value>
      <webElementGuid>75f1cf14-240a-4471-af19-ecfb658ec219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>32a39e78-3a3a-4496-802b-f7037064b14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>e217bf7f-fa1e-49a3-992f-84f35f84b633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>bbc7bbfe-dfb6-4d7b-95e2-03ffc47ace9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-psxfltpo60cc</value>
      <webElementGuid>92be685b-9c14-40fb-90f5-224b8b387417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4bc468c8-c342-40d8-bf4c-bc5458675782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>108a5aa5-ecfc-4d6b-935b-362d6027b6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>debe8135-9fa2-4967-92d1-5a4e5ea2c227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiModal-root MuiDialog-root css-126xj0f&quot;]/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper css-ekeie0&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthSm css-e4g4kz&quot;]/form[1]/div[@class=&quot;MuiDialogContent-root css-13t24bo&quot;]/div[1]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>8f193827-ae4f-48ac-ba61-50c8b695cbbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-psxfltpo60cc']</value>
      <webElementGuid>65480fb4-f95f-4581-b84e-d36b5abee230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/iframe</value>
      <webElementGuid>a92f1a68-5e90-448b-9c9b-b19ad7fed3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lc_Gt4ZAAAAAOm9_29UIGEij29l1W7MMGxvSOSU&amp;co=aHR0cHM6Ly9teS5rYXRhbG9uLmNvbTo0NDM.&amp;hl=en&amp;type=image&amp;v=CHIHFAf1bjFPOjwwi5Xa4cWR&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=dinu3gjeidv8' and @name = 'a-psxfltpo60cc']</value>
      <webElementGuid>f0f7f13e-0ffa-4870-a115-1d832a8a4554</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
