<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(I didn, , t get the email)_a-_e24129</name>
   <tag></tag>
   <elementGuidId>e165f561-8757-4425-9224-d39f50a44d8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-6k39ir17uzk&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-6k39ir17uzk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>90d52bb8-803c-4a0e-a2aa-04169a6db098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>1e27c203-049e-4faa-9aea-34680751898e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lc_Gt4ZAAAAAOm9_29UIGEij29l1W7MMGxvSOSU&amp;co=aHR0cHM6Ly9teS5rYXRhbG9uLmNvbTo0NDM.&amp;hl=en&amp;type=image&amp;v=CHIHFAf1bjFPOjwwi5Xa4cWR&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=r2so71d1dgth</value>
      <webElementGuid>f400e486-1b74-4392-a84f-e61822fd0fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>f1342bf8-dbb0-4c84-a774-5bca37e39a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>fb18847e-93fe-4a9b-aef6-5c48b8e4502a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>e81ede42-d7ec-4a8d-8ac2-c1c6b4e637bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-6k39ir17uzk</value>
      <webElementGuid>7c26884a-6445-4ab7-85c9-f75276e4e003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4be1dd79-5d7f-41c2-a30c-3ea4dd130063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>77395e49-f29c-431b-b843-5a82fab74f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>42737220-9d75-4295-b951-44a07752e82b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiModal-root MuiDialog-root css-126xj0f&quot;]/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper css-ekeie0&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthSm css-e4g4kz&quot;]/form[1]/div[@class=&quot;MuiDialogContent-root css-13t24bo&quot;]/div[1]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>bf46bbc7-267e-4292-b079-672e1e2b1853</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-6k39ir17uzk']</value>
      <webElementGuid>07f5f7a2-8e96-4bbf-bc66-7dd2860d3218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/iframe</value>
      <webElementGuid>9cd5fdb3-2074-4d58-b8c3-e5074138f98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lc_Gt4ZAAAAAOm9_29UIGEij29l1W7MMGxvSOSU&amp;co=aHR0cHM6Ly9teS5rYXRhbG9uLmNvbTo0NDM.&amp;hl=en&amp;type=image&amp;v=CHIHFAf1bjFPOjwwi5Xa4cWR&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=r2so71d1dgth' and @name = 'a-6k39ir17uzk']</value>
      <webElementGuid>a0641d73-1210-42a4-82d8-615c5e787c09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
